name: bloc_example
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_gen: ^5.3.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  get_it: ^7.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  infinite_scroll_pagination: ^3.2.0
  injectable: ^2.1.1
  intl: ^0.17.0
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1
  shared_preferences: ^2.1.0


dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.3
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.2
  mocktail: ^0.3.0
  retrofit_generator: ^6.0.0+3
  very_good_analysis: ^4.0.0+1


flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  generate: true
